### ISSUE TITLE
Improve doc of examples - how to run

### ISSUE THREAD

**Issue by cmoulliard** [rhuss/docker-maven-plugin#107]
Should be great to extend the text of the samples to explain (after running docker maven plugin generating the image) how the user can use the image and run the tomcat/jetty container with jkia

https://github.com/rhuss/docker-maven-plugin/blob/master/doc/examples.md

**Comment by rhuss** [comment]
I just added an example how to run `docker:start` with the Jolokia demo image so that one can connecto the agent. 

Is this want you meant ? --> https://github.com/rhuss/docker-maven-plugin/blob/integration/doc/examples.md

Or more generally how to use `jolokia/java-jolokia` as a base image (but that's probably out of scope here).
