### ISSUE TITLE
External Dockerfile support?

### ISSUE THREAD

**Issue by dugchez** [rhuss/docker-maven-plugin#126]
manual.md says:

"In a future version you will be able to specify alternatively an own Dockerfile (possibly containing maven properties) for better customization."

It also says:

"dockerFileDir specifies a directory containing an external Dockerfile that will be used to create the image."

The ChangeLog for version 0.11.0 states external Dockerfiles are supported.

An example would be helpful. I would assume, for example, that when an external Dockerfile is used the "from" element within a "build" section should be omitted.

**Comment by rhuss** [comment]
That's true, external Dockerfiles are supported by using `dockerFileDir` which takes precedence over the on-the-fly Dockerfile generation. You can use still an assembly to add you artifacts, though. 

It might be that, the config syntax will still change until 1.0 since we might change `dockerFileDir` to  `dockerFile` (so that you can use multiple dockerfiles which all add the same files). But the migration will be trivial and straight forward. 

I'll clean up the manual, thanks for pointing this out.

**Comment by twz123** [comment]
By the way, is there any way to see the output of the Dockerfile RUN commands? If not, maybe it's worth mentioning this in the docs?

**Comment by rhuss** [comment]
We are on it in #36 , hope that I will get to this pretty soon ....

**Comment by connaryscott** [comment]
glad to hear that it's theoretically possible, any examples on how to USE dockerFileDir?

**Comment by jessezhao2017** [comment]
where is the sample???

**Comment by rhuss** [comment]
Here is one https://github.com/fabric8io/docker-maven-plugin/blob/master/samples/data-jolokia-demo/pom.xml#L355-L396 but agree, the could be a more comprehensive one, too. Happy about any PR, but will try to add one soon.
