### ISSUE TITLE
Support shell syntax

### ISSUE THREAD

**Issue by drallgood** [rhuss/docker-maven-plugin#130]
Right now, the CMD is specified in exec form no matter what.
This means, that you can't really use variables in you command (adding `sh -c`to the beginning doesn't always work).

It would be nice if you could choose between shell and exec form.

**Comment by akobiakov** [comment]
Agree with @drallgood: current way of parsing the "command" field looks a bit odd and counterintuitive for a docker user. I'd prefer a syntax which looks similar to [official docker forms for CMD](https://docs.docker.com/reference/builder/#cmd) (shell/exec). Something like:
```xml
<command>
    <shell>java -jar /opt/demo/server.jar</shell>
</command>
```
and 
```xml
<command>
    <exec>java /opt/demo/server.jar</exec>
    <params>
        <param>-jar</param>
        <param>/opt/demo/server.jar</param>
    </params>
</command>
```
What do you think, guys?

**Comment by drallgood** [comment]
I like the first one better. It's easier to create/read.

Implementation-wise, the easiest solution would be to just check for "sh -c" in the command and use the shell-syntax in case it's found.

**Comment by rhuss** [comment]
I like @akobiakov suggestion, since it is more explicit. I always hesitate a bit trying to be too "clever" (here: changing the Dockerfile syntax depending on the *value* a user gives). Also, having dedicate `param` tags would make it easier to provide args with spaces (don't know how well quoting works within Dockerfiles). 

I would introduce this for 0.12.0 since it requires a (slight) configuration syntax change.

**Comment by drallgood** [comment]
Awesome! :)

**Comment by rhuss** [comment]
Well, if anyone wants to work on that, it would be awesome :) I'm happy for each PR since I still have quite some other stuff to work on for 0.11.3 ;-) Please see this [document](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/contributing.md) for how to contribute (but you probably already know this). And please let us know in this issue if some of you starts to work on this (in order to avoid duplicate efforts).

**Comment by akobiakov** [comment]
Due to a [bug](https://github.com/docker/docker/pull/11203) in dockerfile parser we have to use a shell format which is currently not supported by the plugin, so an external Dockerfile is the only workaround for now.
Therefore, I'd be glad to undertake this enhancement.

**Comment by rhuss** [comment]
Perfect, simply submit a PR when you are done, I will happily review and apply it ;-)

Thanks!

**Comment by alan-czajkowski** [comment]
I've reported a similar issue here: #149

I describe in detail why ```sh -c``` does not work (according to documentation, and how to make it work, which the plugin does not support.

**Comment by alan-czajkowski** [comment]
is there an ETA on this? would be nice to have this feature (as I don't like the Spotify Maven Docker plugin)

**Comment by akobiakov** [comment]
@alan-czajkowski We're working on it. My colleague is going to create a PR tomorrow.

**Comment by akobiakov** [comment]
The PR is here: https://github.com/rhuss/docker-maven-plugin/pull/156

**Comment by rhuss** [comment]
Cool ;-) 'hope that I can review and merge it in ASAP, hopefully this week.

**Comment by alan-czajkowski** [comment]
awesome work guys, once 0.12.0 comes out then i will test it out and #149 may become an obsolete issue

**Comment by rhuss** [comment]
Yeah, finally in in 0.12.0. 'will be released this week, stay tuned .... ;-)

Thanks again for your support and you patience ...
