### ISSUE TITLE
UNIX socket support

### ISSUE THREAD

**Issue by rassie** [rhuss/docker-maven-plugin#148]
I don't know if this is intended (documentation implies that it might be), but I'm sorely missing UNIX socket support for docker. One of the reasons is that we are running Jenkins instances in containers and mount `/var/run/docker.sock` into each container, so that Jenkins could build other docker images. Working with TCP becomes vastly more complicated in this situation.

**Comment by vauvenal5** [comment]
+1

**Comment by jgangemi** [comment]
i don't know what the likelihood of this is going to be given it's not portable across build environments, etc, and i know that is one of the goals of this plugin.

have you tried using the ambassador pattern as a work around for this: https://docs.docker.com/articles/ambassador_pattern_linking/

**Comment by rhuss** [comment]
In fact, Unix socker support is not so easy when coming from Java. As @jgangemi said, portability is one of the main key features. However, I also think that it shouldn't harm to allow unix socket access for Linux plattforms as an optional way for accessing the Docker daemon as long it doesn't require some strange packaging of the plugin because of native libs to be included.

Maybe we can collect here what are the technical possibilities to do so ? (I know, there are some libs for this out there, but never checked them really)

**Comment by jgangemi** [comment]
marking as closed
