### ISSUE TITLE
Specify the user for assembly.xml

### ISSUE THREAD

**Issue by arun-gupta** [rhuss/docker-maven-plugin#175]
Add the ability so that the dependencies from `assembly.xml` are copied with a specific user. Currently they are always done as `root`.

**Comment by rhuss** [comment]
Unfortunately this is not so easy for now because of this [Docker issue](https://github.com/docker/docker/issues/6119). I will implement the workaround to RUN a "chown" if the a user is specified, but this adds some extra layers.

We already had some discussions around this in #53 .

BTW, for your use case you can come around this limitation completely (works already with the current version), by specifiying `/opt/jboss/wildfly/standalone/deployments` as `basedir` in the pom.xml and in the assembly.xml use a `outputDir` of `.` This will copy only the WAR file as root (and leave the directory untouched).
