### ISSUE TITLE
docker:build - Using <env> which refers to another env fails

### ISSUE THREAD

**Issue by davsclaus** [rhuss/docker-maven-plugin#185]
Due to that fabric8 issue with 2x CORS headers we need to apply the workaround @rhuss found.

But for the WAR images then the jolokia agent cannot find the jolokia-access.xml file from within the WAR.

A solution for that is to configure the CATALINA_OPTs
```
      <plugin>
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>${docker.maven.plugin.version}</version>
        <configuration>
          <images>
            <image>
              <name>${docker.image}</name>
              <build>
                <from>${docker.from}</from>
                <assembly>
                  <descriptorRef>${docker.assemblyDescriptorRef}</descriptorRef>
                </assembly>
                <env>
                  <CATALINA_OPTS>-javaagent:/opt/tomcat/jolokia-agent.jar=host=0.0.0.0,port=8778,agentId=$HOSTNAME,policyLocation=jar:file:///maven/ROOT.war!/WEB-INF/classes/jolokia-access.xml</CATALINA_OPTS>
                </env>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
```

But then with `agentId=$HOSTNAME` then that fails when running the image with docker
```
davsclaus:~/workspace/quickstarts/quickstarts/war/camel-servlet (warfix)/$ docker run -i -t -p 8080:8080 -p 8778:8778 a5994e9ee3d0
Checking *.war in /maven
Linking /maven/ROOT.war --> /opt/tomcat/webapps/ROOT.war
Using CATALINA_BASE:   /opt/tomcat
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /opt/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar:/opt/tomcat/bin/tomcat-juli.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:384)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.IllegalArgumentException: jolokia: Invalid option 'agentId='. Ignoring
	at org.jolokia.jvmagent.JvmAgentConfig.split(JvmAgentConfig.java:112)
	at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:46)
	at org.jolokia.jvmagent.JvmAgent.premain(JvmAgent.java:67)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted
```

**Comment by davsclaus** [comment]
To reproduce this issue you can add `agentId=$HOSTNAME` back into this line
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/war/camel-servlet/pom.xml#L145

And then do a 

    mvn package docker:build

**Comment by rhuss** [comment]
Could it be, that the Jolokia agent is very old ? The base image `fabric8/tomcat-8.0` uses Jolokia 1.2.3, `agentId` was introduced in 1.2.0 but it could be, that I forhot that for the JVM agent option. 

will check that tomorrow

**Comment by davsclaus** [comment]
Ah maybe, I had a fabric8/java image running and it has been upgraded to latest jolokia
```
{
timestamp: 1433486190,
status: 200,
request: {
type: "version"
},
value: {
protocol: "7.2",
config: {
maxDepth: "15",
maxCollectionSize: "0",
maxObjects: "0",
discoveryEnabled: "true",
agentContext: "/jolokia",
historyMaxEntries: "10",
agentId: "521b64941175",
agentType: "jvm",
debug: "false",
debugMaxEntries: "100"
},
agent: "1.3.1",
info: {
product: "tomcat",
vendor: "Apache",
version: "8.0.23"
}
}
}
```

as I was working on some spring boot support.

**Comment by davsclaus** [comment]
PS: Maybe jolokia should output its version when it logs something such as

```
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.26:8778/jolokia/
```

**Comment by davsclaus** [comment]
We should likely try to upgrade our docker images from this project. @rhuss you will find it familar
https://github.com/fabric8io/docker-appserver

Afair last time I tried that it had some troubles doing so

**Comment by rhuss** [comment]
Good point, but I'm a bit ambivalent /wr to log output. I tend to log out only information which are either dangerous (no access restrictor) or when an optional desired feature does't work (multicast) because I don't know in which environment Jolokia is running and people tend to be picky about their logs (for a good reason). The JVM agent can safely log only on standard out which is also a bit rude.

You can always get the version with a 'curl <jolokia-url>' which returns within its metadata.

**Comment by rhuss** [comment]
I will update `fabric8io/docker-appserver` to the latest jolokia and check for this bug there.

BTW, I updated the base image of `fabric8/java` (which is `jolokia/jolokia-java:latest`) and triggered a rebuild of `fabric8/java`. 

We should probably consider a version strategy very soon, since inheritance with `latest` (or SNAPSHOT) images is inherently dangerous. The current tags (aka versions) from this base image point to the version of the enclosed Java and is not the version of the image itself.

Now that Docker also supports labels, I suggest that we switch to a naming scheme where the tag of our images (java, tomcat, etc.) reflect the version of this image and we add the version of the enclosed features (java, jolokia) as docker labels.

There will be the question how to deal with variants of an image, like different JVM versions. Maybe we could encode the variants in the tag name, too (`fabric8io/java:0.5-jdk8`, `fabric8io/java:0.5-jdk7`,...) ...

Unfortunately, Docker itself hasn't a mechanism that would prevent an image with an already existing tag to be pushed again to a registry.

**Comment by davsclaus** [comment]
Btw for the tomcat docker images we may want to add this to workaround java7 bug
http://stackoverflow.com/questions/27582254/how-to-speed-up-tomcat-sessionidgenerator

I have tried that with and without and on my laptop tomcat in docker would delay several minutes before booting up. 

In our forge commands to fabric enable a mvn project we do this now with for the spring-boot
https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/helper/DockerSetupHelper.java#L58

**Comment by rhuss** [comment]
This is already included in the docker-appservers [startup script](https://github.com/fabric8io/docker-appserver/blob/master/tomcat/templates/deploy-and-run.sh#L12)

BTW, I found out that there error above is due to that `$HOSTNAME` is not evaluated when the container starts but when the image is build (and hence is empty so that the agent can't parse this as option).

It's better to setup CATALINA_OPTS in the startup script. I'll fix that overthere (a long with some other issues I found), so that it should work again.

**Comment by rhuss** [comment]
BTW, if you try to run a vanilla `docker run -t -i fabric8/tomcat-8.0` you get the same error for the same reason.

**Comment by rhuss** [comment]
I added rhuss/jolokia#199 for allowing a delayed evaluation of the variable. Until know I would omit the agentId since it default contains the hostname anyway.

**Comment by davsclaus** [comment]
Ah perfect we can track the issue in the docker plugin issue tracker and close this one.

**Comment by davsclaus** [comment]
Ups this was in the docker maven plugin, - but I guess its fine to close anyway as #199 fixes this

**Comment by rhuss** [comment]
I updated `fabric8/tomcat-7.0` so that it should work out of the box again. Should be available soon at docker hub, build is still pending.
