### ISSUE TITLE
Documentation on runCmd / runCmds

### ISSUE THREAD

**Issue by computerlyrik** [rhuss/docker-maven-plugin#223]
The Documentation in User Manual section docker:build tells about the "run" element.

Is this correct? For me it is still running on <runCmds> and <runCmd>

**Comment by rhuss** [comment]
I changed `runCmd` to `run` to better mimic the Dockerfile syntax (which I also try for the other options). It's a bit of a tradeoff because `<run>` is also use a level higher for the run-configuration when creating and starting containers. 

I hope this isn't to confusing.

If you don't mind I close this issue, feel free to reopen it in case.
