### ISSUE TITLE
autoPull "always" should send --pull flag

### ISSUE THREAD

**Issue by kuhnroyal** [rhuss/docker-maven-plugin#228]
When building an image with a Dockerfile and autoPull set to "always", the --pull option should be included in the Docker API call. (API 1.16+). This will essentially mirror the behavior without having a Dockerfile.

**Comment by rhuss** [comment]
Version 0.13.8 (will be out in a minute) now parsed a Dockerfile and extract the `FROM` base image so that it can be treated like the base image when working without Dockerfiles (`<from>`). So this should does exactly what you describe (although without using the Docker API). 

I'll close the issue now, feel free to reopen it in case I misunderstood your use case.
