### ISSUE TITLE
extra directories created under target/docker during build

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#262]
the directory structure of `target/docker` should look like this:
```
target/
  docker/
    build/
    tmp/
    work/
```
instead it looks like this (assume maven basedir = `root/parent/child`)
```
target/
  docker/
    root/
      parent/
        child/
          build/
          tmp/
          work/
```
the extra substitution of `basedir` should not occur. 

this doesn't break any functionality but does make it cumbersome to traverse the extra dirs when you want to look at something.

**Comment by rhuss** [comment]
Have to look it up thoroughly after the weekend, but AFAIR we introduced an extra level below `docker/` for each image configured so that they don't interfere when building multiple images. The level below `docker/` reflects the image name (`user/image`), but I'll check that later.

For now: Keep on rocking ... \m/

**Comment by jgangemi** [comment]
lol - it can wait - enjoy your festival!

**Comment by jgangemi** [comment]
this works as expected - closing.
