### ISSUE TITLE
Wait with nothing to wait for waits the whole timeout delay

### ISSUE THREAD

**Issue by mgurov** [rhuss/docker-maven-plugin#276]
Given `wait` config with no `<log>` or `<http>` entries, the `docker:run` will report success after waiting for the max allowed time. 

Expected: no wait and success (my preference) or configuration error. 

Will provide a PR upon request.

**Comment by rhuss** [comment]
You are right, `<wait>` without any condition should be treated as a configuration error,.

If you only use `<time>` this is not interpreted as an timeout but as an amount of milliseconds to wait until to continue without error. Only when combined with one of the other conditions it acts as an timeout. This was changed because of https://github.com/rhuss/docker-maven-plugin/issues/173#issuecomment-111870354

**Comment by mgurov** [comment]
OK, so we do want to wait for the explicitly specified `<time>` when no condition (`log` or `http`) specified. 

The presence of the unrelated `<shutdown>` parameter in the `<wait>` clause makes strict validation bit clumsy IMHO. Besides we probably don't want to wait on start when only the `<shutdown>` parameter is present. How about simply skipping the delay after start on no time or conditions specified, as in following table: 

`<log>/<http>/<url>` | `<time>` | `<effect>`
--- | --- | ---
:white_check_mark:  | :white_check_mark: | `<time>` timeout on `<log>/<http>/<url>` condition
:white_check_mark: | :x: | default timeout on `<log>/<http>/<url>` condition
:x: | :white_check_mark: | pause for `<time>`
:x: | :x: | don't delay after start

**Comment by rhuss** [comment]
Looks good to me. So, an empty `<wait>` is essentially a nop, the other behaviour is actually as it is already implemented IIRC.

**Comment by rhuss** [comment]
Fixed in branch `integration`, available in 0.13.4
