### ISSUE TITLE
Allow different registries for snapshots and releases

### ISSUE THREAD

**Issue by unguiculus** [rhuss/docker-maven-plugin#289]
We're setting up our new Docker infrastructure with Artifactory. I'm thinking about setting up different Docker repos for snapshots and releases as you would do this for Maven artifacts. No sure yet if it makes sense for Docker. Anyways, since Maven deploys to different repos for snapshots and releases (`distributionManagement`), would it be possible to get something similar for Docker, i. e. a way to specify different registries for snapshots and releases?

**Comment by rhuss** [comment]
One feature of docker (which I dislike from the bottom of my heart ;-) is that the registry is part of an image's id: `<registry>/<user>/<name>:<tag>`. So in order to distribute your image on different registry, you need to change the `<name>` within the configuration.

There is some support from d-m-p for pushing to arbitrary registries. You can do this with the image config parameter `<registry>` in the global configuration section. Using this, d-m-p will *temporarily* tag your image with a name containing the registry, docker push it, and then remove this tag again. See also the [manual](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/manual.md#registry-handling) for more details.

So you can use different profiles for snapshot and release configurations. Or you can use `-Ddocker.registry` when calling docker. 

Does this help you ?

**Comment by unguiculus** [comment]
I absolutely agree, having the registry in the image or Dockerfile is a bad idea. I never specify a registry in the FROM clause and re-tag the image after building it in order to push it to a registry.

I already thought about using a Maven profile or a command-line switch but you would have to explicitly specify it whereas Maven knows which repo to deploy to based on whether the version is a snapshot or not.

**Comment by rhuss** [comment]
Please note, that the d-m-p isn't agnostic about the maven coordinates it is configured for. So it has no idea whether it works on a snapshot or not (and you can also configure multiple, different, images, too). One could establish a notion of 'latest' being a 'SNAPSHOT' (the closes thing, I guess), and the introduce sth like that. 

If it would work with profiles for you (you can use `combine.self="override"` as described here to avoid duplication of configuration), I would be quite happy in order to keep the complexity of this plugin small. 

If not, let's think about how we could establish this mapping latest -> SNAPSHOT ...

**Comment by unguiculus** [comment]
I'm withdrawing the issue now. I was playing with this idea when setting up Docker repos in our new Artifactory instance.
