### ISSUE TITLE
Support for switching USER

### ISSUE THREAD

**Issue by mike-williams** [rhuss/docker-maven-plugin#352]
Hi is it possible to the current user to another directly within plugin? For example the Dockerfile that I am basing from is using 'jboss' user but I need to switch back to 'root' user (e.g. USER root - in the Dockerfile). So far I have been unsuccessful in replicating this. Thanks in advance for any help.

**Comment by jgangemi** [comment]
@rhuss can confirm but i'm pretty sure you can't switch back and forth between users using the xml configuration. if you have a working `Dockerfile`, i suggest using that as the plugin supports those.

**Comment by mike-williams** [comment]
ok I point the plugin to my own Dockerfile. Thanks for the help

**Comment by rhuss** [comment]
@mike-williams if you use an assembly you can do something like this easily with the `user` directive (sorry, saw this issue late).

From the documentation:

 **user** can be used to specify the user and group under which the files should be added. The user must be already exist in the base image. It has the general format 
  `user[:group[:run-user]]`. The user and group can be given either as numeric user- and group-id or as names. The group id is optional. If a third part is given, then the build changes to user `root` before changing the ownerships, changes the ownerships and then change to user `run-user` which is then used for the final command to execute. This feature might be needed, if the base image already changed the user (e.g. to 'jboss') so that a `chown` from root to this user would fail. 

For example, the image `jboss/wildfly` use a "jboss" user under which all commands are executed. Adding files in Docker always happens under the UID root. These files can only be changed to "jboss" is the `chown` command is executed as root. 
  
For the following commands to be run again as "jboss" (like the final `standalone.sh`), the plugin switches back to user `jboss` (this is this "run-user") after changing the file ownership. For this example a specification of `jboss:jboss:jboss` would be required.
