### ISSUE TITLE
Push to private repo using ~/.docker/config.json fails

### ISSUE THREAD

**Issue by rodlogic** [rhuss/docker-maven-plugin#368]
This is the error:
```
INFO] --- docker-maven-plugin:0.13.8:push (default-cli) @ my-image ---
[INFO] DOCKER> ... The push refers to a repository [295240448163.dkr.ecr.us-east-1.amazonaws.com/database-connector] (len: 1)
[INFO] DOCKER> ... 93f8c73a5e63 Preparing
[ERROR] DOCKER> Post https://295240448163.dkr.ecr.us-east-1.amazonaws.com/v2/my-image/blobs/uploads/: no basic auth credentials
```

I have performed the ```docker login``` and I am able to push using ```docker push``` successfully.

**Comment by rhuss** [comment]
Could you please just have a quick look into `~/.docker/config.json and check whether you registry is mentioned there with an `https://` prefix or only as host:port ?

If the former, than probably this [issue](https://github.com/rhuss/docker-maven-plugin/pull/367) applies which will be fixed in the next release.

**Comment by rodlogic** [comment]
It does:
```
"auths": {
                "https://295240448163.dkr.ecr.us-east-1.amazonaws.com": {
```
I have also confirmed that the latest 0.14.0-SNAPSHOT works as expected.

Do you have a target date for the 0.14 release?

**Comment by rhuss** [comment]
good to know that it works for you :) /wrt to a release, there is no ETA yet. Could be that I'll do a 0.13.9 before tackling 0.14.0 with support for `docker compose` config format.
