### ISSUE TITLE
the sledgehammer still exists during parallel execution runs

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#372]
if you run a reactor build in parallel, the plugin will stop any containers that get started during overall execution of the build.

**Comment by rhuss** [comment]
Thanks for your PR. I picked up the idea, however did the implementation slightly different (by moving the burden to filtering on PomLabel into the ContainerTracker). 'hope thats ok for you.

**Comment by jgangemi** [comment]
works for me - would it be possible to get a `0.13.9` release for this or is `0.14.0` a day or two away? this fix will allow me to finally switch over to running integration tests against containers at the day job.

**Comment by rhuss** [comment]
Just  released 0.13.9 with this change only :) since I still need a bit for 0.14.0 (where we possible should present docker compose support already). Thanks for the initial PR and kicking the wire.

Also, I plan to move this repository to `fabric8/docker-maven-plugin` in order to join a larger community with some infrastructure already set up (mailing-list, IRC hannels). 'have to discuss this with our team still, though. Maybe 0.14.0 will be the first release there ;).
