### ISSUE TITLE
Provide forcePull option

### ISSUE THREAD

**Issue by jegr78** [rhuss/docker-maven-plugin#96]
It would be great to have an option, to force pulling an image. I'm currently having the issue, that my images already exist and so the pull option doesn't download the latest image from my private registry. I'd like to perform some kind of testing during CI (Jenkins with slaves) and need the possibility to force pulling of the latest availiable images from my private registry before running/starting the containers.

**Comment by jgangemi** [comment]
the docker api already has an option to allow this so it just needs to be added in. depends on #108.

**Comment by kuhnroyal** [comment]
This should work in 0.11.1.
See #88 and d77b597dc88a6caf25813595384a833452ae4b1e

**Comment by jgangemi** [comment]
hrm - yeah - it looks like that option was added to the 1.17 api and doesn't exist in 1.15, so your solution handles more cases.

**Comment by kuhnroyal** [comment]
What do you guys think about this?

```xml
<autoPull>
    <enable>true</enable><!-- defaults to true -->
    <force>true</force><!-- defaults to false -->
</autoPull>
```

**Comment by jgangemi** [comment]
i would be ok with having a single tag that had multiple options (enum) of `off`, `enabled`, `force` where `force` implies `enabled but let's see what @rhuss says.

**Comment by kuhnroyal** [comment]
True, that would work.

**Comment by rhuss** [comment]
I'm also more for the enum approach (but more like `true`/`false`/`always` or `on`/off`/`always`) since having two independent options leads to non sensible combinations (like enable == false, force == true)

**Comment by rhuss** [comment]
As mentioned in #112, `autoPull` with `always` is probably not  a good idea for the image which are build by this maven build when doing a `docker:start`.  With `autoPull=always` you will integration test images from the registry (if any is already pushed) and not the one just build (and stored in the docker host). 

So I wonder, whether a global 'forceMode' is a good idea anyway. It is probably more suited for being part of the `<image>` and `<run>` and `<build>` sections. 

If used globally I could imagine the following algorithm, when `autoPull == always`:

* For `<build>` always pull any base image.
* For `<run>` only pull images which don't have a `<build>` section, since these are supposed to be created outside this build and can safely be pulled always.

What's your opinion on this ?

Since I'm going to make a release today, I will save this feature for the next until we decided on the feature (and it would be cool to have autoPull support on all levels: (global), (image), (build and run) with more specific configs overwriting the more general ones.

**Comment by rhuss** [comment]
I'll will implement it like I described above, since I think that's a reasonable default. One can always add addition pull modes later on, too ....
